pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: "./outputs/car-turn-16-former"

train_data:
  video_path: "data/car-turn.mp4"
  prompt: "a jeep car is moving on the road"
  n_sample_frames: 16
  width: 512
  height: 512
  sample_start_idx: 0
  sample_frame_rate: 2

validation_data:
  prompts:
    - "a jeep car is moving on the road"
    - "a jeep car is moving on the snow"
    - "a jeep car is moving on the road, cartoon style"
    - "a sports car is moving on the road"
  video_length: 16
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
